transfer:
  # Optional (default: 4)
  concurrency: 10
  # Optional (default: 'transfer_')
  transferPrefix: "transfer_"
  # This directory is appended to the 'clusters:...:hcfsNamespace' value to store the transfer package for hive export/import.
  # Optional (default: '/apps/hive/warehouse/export_')
  exportBaseDirPrefix: "/apps/hive/warehouse/export_"
clusters:
  LEFT:
    # Set for Hive 1/2 environments
    legacyHive: true
    # Is the 'Hadoop COMPATIBLE File System' used to prefix data locations for this cluster.
    # It is mainly used as the transfer location for metadata (export)
    # If the primary storage for this cluster is 'hdfs' than use 'hdfs://...'
    # If the primary storage for this action is cloud storage, use the
    #    cloud storage prefix. IE: s3a://my_bucket
    hcfsNamespace: "<hdfs://namespace>"
    hiveServer2:
      uri: "<LEFT-cluster-jdbc-url>"
      connectionProperties:
        user: "*****"
        password: "*****"
      # Standalone jar file used to connect via JDBC to the LEFT environment Hive Server 2
      # NOTE: Hive 3 jars will NOT work against Hive 1.  The protocol isn't compatible.
      jarFile: "<environment-specific-jdbc-standalone-driver>"
  RIGHT:
    legacyHive: false
    # Is the 'Hadoop COMPATIBLE File System' used to prefix data locations for this cluster.
    # It is mainly used to as a baseline for where "DATA" will be transfered in the
    # STORAGE stage.  The data location in the source location will be move to this
    # base location + the extended path where it existed in the source system.
    # The intent is to keep the data in the same relative location for this new cluster
    # as the old cluster.
    # If the LEFT and RIGHT clusters are share the same cloud storage, then use the same
    # hcfs base location as the LEFT cluster.
    hcfsNamespace: "<hdfs://namespace>"
    hiveServer2:
      uri: "<RIGHT-cluster-jdbc-url>"
      connectionProperties:
        user: "*****"
        password: "*****"
      # Standalone jar file used to connect via JDBC to the LEFT environment Hive Server 2
      # NOTE: Hive 3 jars will NOT work against Hive 1.  The protocol isn't compatible.
      jarFile: "<environment-specific-jdbc-standalone-driver>"
    partitionDiscovery:
      # Addition HMS configuration needed for this "discover.partitions"="true"
      auto: true
      # When a table is created, run MSCK when there are partitions.
      initMSCK: true
